config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  ##------ STATIC ROUTES------------------------------------------------------------- ##
  #
  get 'about-us' => 'home#about_us', :as => :about_us
  get 'privacy-policy' => 'home#privacy_policy', :as => :privacy_policy
  #
  ##------ END STATIC ROUTES-------------------------------------------------------------##




  ##------FRONTEND ROUTES--------------------------------------------------------##
  #
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords'
  }

  get 'profile' => 'home#profile', :as => :my_profile
  get '/get-organizations-from-school/:school_id', to: 'home#get_organizations_from_school', :as => :get_organizations_from_school

  #
  ##------END FRONTEND ROUTES--------------------------------------------------------##




  ##------ ADMIN ROUTES-------------------------------------------------------------##
  #
  namespace :admin, :as => nil do
    get '/get-state-from-country/:country_id', to: 'admin#get_state_from_country', :as => :get_state_from_country
    get '/search-all', to: 'home#search_all', :as => :search_all
    get '/' => 'home#index', :as => :home_admin

    resources :users

    resources :airports

    resources :schools do
      resources :organizations
    end
  end
  #
  ## --------END ADMIN ---------------------------------------------------------------##
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :school
  belongs_to :state
  belongs_to :country

  validates_presence_of :slug, :name, :address, :city, :state_id, :zip, :country
  validates_uniqueness_of :slug, case_sensitive: false , scope: :school_id

  extend FriendlyId
  friendly_id :name, use: :slugged

  before_save :update_organization_info
  before_update :update_organization_info

  EDIT_TAB_NAMES = {
      :details => 'details',
  }

  def update_organization_info
    begin
      #find lat and long value
      if self.city && self.state
        coordinates = Geocoder.coordinates("#{self.address}, #{self.city}, #{self.state.name}")
        if(coordinates != nil && coordinates.length >= 2)
          self.latitude = coordinates[0]
          self.longitude = coordinates[1]
        else
          self.latitude = nil
          self.longitude = nil
          #raise "Cannot find lat & long value from your location. Please update your city and state!"
        end
      end
    rescue

    end
  end

  def should_generate_new_friendly_id? #will change the slug if the name changed
    name_changed?
  end

  def self.to_collection_of_select
    order(name: :desc).pluck('name, name')
  end

  def get_students
    return User.where(:school => self.school.name, :organization => self.name)
  end

  def get_students_without_school
    return User.where(:organization => self.name)
  end
end

app/controllers/admin/organizations_controller.rb
require 'app_utils'

class Admin::OrganizationsController < Admin::AdminController
  before_action :get_school
  before_action :init_item, :except => [:new, :create]

  def new
    @organization = Organization.new(:school_id => @school.id,
                                     :web_address => @school.web_address,
                                     :phone => @school.phone,
                                     :address => @school.address,
                                     :city => @school.city,
                                     :state_id => @school.state_id,
                                     :zip => @school.zip,
                                     :country_id => @school.country_id)
  end

  def create
    @organization = Organization.new(params_organization)
    @organization.school_id = @school.id
    if @organization.valid?
      @organization.save
      flash[:success] ='Created successfully!'
      redirect_to edit_school_path(@school.slug, :tab => School::EDIT_TAB_NAMES[:organizations])
    else
      render :new
    end
  end

  def edit
    add_breadcrumb 'Dashboard', edit_school_path(@school.slug, :tab => School::EDIT_TAB_NAMES[:organizations])
    add_breadcrumb 'Edit', edit_school_path(@school.slug, :tab => School::EDIT_TAB_NAMES[:organizations]), title: 'Organizations'

    @current_tab = params[:tab].blank? ? 'details' : params[:tab]
  end

  def update
    if @organization.update(params_organization)
      flash[:success] ='Updated successfully!'
      redirect_to edit_school_path(@school.slug, :tab => School::EDIT_TAB_NAMES[:organizations])
    end
  end

  def destroy
    if @organization.destroy
      flash[:success] ='Destroy successfully!'
    else
      flash[:error] ='Destroy failed!'
    end
    redirect_to edit_school_path(@school.slug, :tab => School::EDIT_TAB_NAMES[:organizations])
  end

  def student_list
    student_page = params[:student_page].to_i < 1 ? 1 : params[:student_page].to_i
    @student_page_size_name = 'students'
    @student_page_size_value = per_page(@student_page_size_name)
    @students = @organization.get_students.paginate(page: student_page, per_page: @student_page_size_value)

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def get_school
    @school = School.friendly.find(params[:school_id])
  end

  def init_item
    @organization = Organization.friendly.find(params[:id])
  end

  def params_organization
    params.require(:organization).permit(:name, :web_address, :address, :city, :state_id, :country_id, :zip, :phone)
  end
end

app/views/admin/organizations/_edit_form.html.erb
<%= simple_form_for(@organization, url: school_organization_path(@school.slug, @organization.slug), html: {remote: true}) do |f| %>
    <%= f.input :name %>
    <%= f.input :web_address %>
    <%= f.input :phone %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.association :country, prompt: 'Country', :input_html => {:class => 'multiselect'} %>
    <%= f.association :state, prompt: 'State', :input_html => {:class => 'multiselect'} %>
    <%= f.input :zip %>
    <%= f.submit 'Submit', class: 'btn btn-primary', 'data-disable-with' => 'Submitting...' %>
<% end %>

<%= render :partial => 'admin/partials/scripts/country_state_script', :locals => {:form_name => 'organization'} %>

app/views/admin/organizations/_new_form.html.erb
<%= simple_form_for @organization, :url => school_organizations_path(@school.slug), html: {remote: true} do |f| %>
    <div class="modal-body">
      <%= f.input :name %>
      <%= f.input :web_address %>
      <%= f.input :phone %>
      <%= f.input :address %>

      <div class="row">
        <div class="col-sm-6">
          <%= f.association :country, prompt: 'Country', :input_html => {:class => 'multiselect'} %>
        </div>
        <div class="col-sm-6">
          <%= f.association :state, prompt: 'State', :input_html => {:class => 'multiselect'} %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <%= f.input :city %>
        </div>
        <div class="col-sm-6">
          <%= f.input :zip %>
        </div>
      </div>
    </div>

    <div class="modal-footer">
      <%= f.submit 'Submit', class: 'btn btn-primary', 'data-disable-with' => 'Submitting...' %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
<% end %>

<%= render :partial => 'admin/partials/scripts/country_state_script', :locals => {:form_name => 'organization'} %>

app/views/admin/organizations/_organization.html.erb
<tr>
  <td><%= organization.name %></td>
  <td><%= organization.address %></td>
  <td></td>
  <td class="text-right">
    <%= link_to raw('<i class="fa fa-edit"></i>'), edit_school_organization_path(@school.slug, organization.slug), class: 'btn btn-default' %>
    <%= link_to raw('<i class="fa fa-trash"></i>'), school_organization_path(@school.id, organization.slug), class: 'btn btn-danger', data: {confirm: 'Are you sure?', method: :delete} %>
  </td>
</tr>

app/views/admin/organizations/edit.html.erb
<div class="box">
  <div class="box-header page-title">
    <p><%= @organization.name %></p>
    <% if @organization.web_address %>
        <h4>
          <a href="http://<%= @organization.web_address.gsub('http://', '') %>" target="_blank" class="red">
            <%= @organization.web_address %>
          </a>
        </h4>
    <% end %>
  </div>
  <div class="box-body">
    <div class="menu-tabs">
      <i class="fa fa-align-justify"></i>
      <span class="text"><%= @current_tab.gsub('_', ' ').titleize %></span>
      <span class="caret"></span>
    </div>

    <div class="tab-panel nav-tabs-custom">
      <ul class="nav nav-tabs">
        <% Organization::EDIT_TAB_NAMES.each_value do |tab_name| %>
            <li <%= 'class=active' if @current_tab == tab_name %>>
              <%= link_to tab_name.titleize.gsub('And', '&'), edit_school_organization_path(@school.slug, @organization.slug, :tab => tab_name), 'data-push' => true %>
            </li>
        <% end %>
      </ul>

      <div class="tab-content">
        <div class="tab-pane slide-right in active">
          <% if @current_tab == Organization::EDIT_TAB_NAMES[:details] %>
              <div id="organization-details-section">
                <%= render :partial => 'edit_form' %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/organizations/new.js.erb
$('#popupModal .modal-content').html("<%= j(render 'new_form') %>");
$('#popupModal .modal-content').prepend("<%= j(render 'layouts/new_modal_title', title: 'Create New Organization' ) %>");
$('#popupModal').modal('show');

app/views/admin/organizations/student_list.js.erb
$('#popupModal .modal-content').html("<%= escape_javascript(render :partial => 'admin/schools/edit/tab_students') %>");
$('#popupModal .modal-content').prepend("<%= j(render 'layouts/new_modal_title',
title: "[#{@students.total_entries}] #{@students.total_entries > 1 ? 'Students' : 'Student'} Of #{@organization.name}" ) %>");
$('#popupModal').modal('show');

app/views/admin/organizations/update.js.erb
$('#organization-details-section').html("<%= j(render 'edit_form') %>");