config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  ##------ STATIC ROUTES------------------------------------------------------------- ##
  #
  get 'about-us' => 'home#about_us', :as => :about_us
  get 'privacy-policy' => 'home#privacy_policy', :as => :privacy_policy
  #
  ##------ END STATIC ROUTES-------------------------------------------------------------##




  ##------FRONTEND ROUTES--------------------------------------------------------##
  #
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords'
  }

  get 'profile' => 'home#profile', :as => :my_profile
  get '/get-organizations-from-school/:school_id', to: 'home#get_organizations_from_school', :as => :get_organizations_from_school

  #
  ##------END FRONTEND ROUTES--------------------------------------------------------##




  ##------ ADMIN ROUTES-------------------------------------------------------------##
  #
  namespace :admin, :as => nil do
    get '/get-state-from-country/:country_id', to: 'admin#get_state_from_country', :as => :get_state_from_country
    get '/search-all', to: 'home#search_all', :as => :search_all
    get '/' => 'home#index', :as => :home_admin

    resources :users

    resources :airports

    resources :schools do
      resources :organizations
    end
  end
  #
  ## --------END ADMIN ---------------------------------------------------------------##
end

app/models/airport.rb
class Airport < ApplicationRecord
  belongs_to :state, optional: true
  belongs_to :country, optional: true
  belongs_to :time_zone

  validates_presence_of :name, :code, :time_zone
  validates :code , length: { in: 1..3 }
  validates :code, uniqueness: { case_sensitive: false }

  extend FriendlyId
  friendly_id :code

  def address
    tmp = city
    tmp += ", #{state.name}" if state
    tmp += ", #{country.name}" if country
    return tmp
  end

  def timezone_name
    time_zone.name if time_zone.present?
  end

  def self.get_custom_name(airport)
    airport.present? ? "#{airport.name} (#{airport.code})" : 'Airport: TBD'
  end

  def self.get_custom_code(airport)
    airport.present? ? airport.code : 'Airport: TBD'
  end
end

app/controllers/admin/airports_controller.rb
require 'app_utils'

class Admin::AirportsController < Admin::AdminController
  before_action :init_item, :except => [:index, :new, :create]
  before_action :get_associated_collection, only: [:new, :create, :edit, :update]
  add_breadcrumb 'Dashboard', :airports_path

  # GET /airports
  def index
    add_breadcrumb 'Index', airports_path, title: 'Airports'

    @key_search = AppUtils.escape_elastic_search_query(params[:q])
    page = params[:page].to_i < 1 ? 1 : params[:page].to_i
    @page_size_name = 'airports'
    @page_size_value = per_page(@page_size_name)

    if @key_search.blank?
      @airports = Airport.order(name: :asc).includes(:state).paginate(page: page, per_page: @page_size_value)
    else
      @airports = Airport.order(name: :asc).includes(:state).where("name ilike '%#{@key_search}%'
                                                                    or code ilike '%#{@key_search}%'
                                                                    or city ilike '%#{@key_search}%'")
                                                              .paginate(page: page, per_page: @page_size_value)
    end
  end

  # GET /airports/new
  def new
    @airport = Airport.new(:country => Country.first)
  end

  # GET /airports/1/edit
  def edit

  end

  # POST /airports
  def create
    @airport = Airport.new(airport_params)
    if @airport.valid?
      @airport.save
      flash[:success] ='Created successfully!'
      redirect_to airports_path
    else
      render :new
    end
  end

  # PATCH/PUT /airports/1
  def update
    if @airport.update(airport_params)
      flash[:success] ='Updated successfully!'
      redirect_to airports_path
    else
      render :edit
    end
  end

  # DELETE /airports/1
  def destroy
    if @airport.destroy
      flash[:success] ='Destroyed successfully!'
    else
      flash[:error] ='Destroy failed!'
    end
    redirect_to airports_path
  end

  private

    def init_item
      @airport = Airport.friendly.find(params[:id])
    end

    def get_associated_collection
      @time_zones = TimeZone.all.order(:name)
    end

    def airport_params
      params.require(:airport).permit(:name, :code, :time_zone, :city, :state_id, :country_id, :time_zone_id) if params[:airport]
    end
end

app/views/admin/airports/_airport.html.erb
<tr>
  <td><%= airport.name %></td>
  <td><%= airport.code %></td>
  <td><%= airport.city %></td>
  <td class="hidden-xs">
    <%= airport.state.name if airport.state %>
  </td>
  <td class="hidden-xs">
    <%= airport.country.name if airport.country %>
  </td>
  <td class="hidden-xs">
    <%= airport.time_zone.name if airport.time_zone.present? %>
  </td>
  <td class="text-right">
    <%= link_to raw('<i class="fa fa-edit"></i>'), edit_airport_path(airport.code), class: 'btn btn-default btn-sm', remote: true %>
    <%= link_to raw('<i class="fa fa-trash"></i>'), airport_path(airport.code), class: 'btn btn-danger btn-sm', data: {confirm: 'Are you sure?', method: :delete} %>
  </td>
</tr>

app/views/admin/airports/_form.html.erb
<%= simple_form_for @airport, html: {remote: true} do |f| %>
    <div class="modal-body">
      <%= f.input :name %>
      <%= f.input :code %>
      <%= f.association :time_zone, prompt: 'Select an time zone' %>
      <%= f.association :country, prompt: 'country' %>
      <%= f.association :state, prompt: 'state' %>
      <%= f.input :city %>
    </div>
    <div class="modal-footer">
      <%= f.submit nil, class: 'btn btn-primary', 'data-disable-with' => 'Submitting...' %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
<% end %>

<%= render :partial => 'admin/partials/scripts/country_state_script', :locals => {:form_name => 'airport'} %>

app/views/admin/airports/edit.js.erb
$('#popupModal .modal-content').html("<%= j(render 'form') %>");
$('#popupModal .modal-content').prepend("<%= j(render 'layouts/new_modal_title', title: 'Edit Airport' ) %>");
$('#popupModal').modal('show');

app/views/admin/airports/index.html.erb
<nav class="navbar navbar-default margin-top-10">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-collapsed-content" aria-expanded="false">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Search Airport</a>
  </div>

  <div class="collapse navbar-collapse" id="nav-collapsed-content">
    <div class="navbar-form navbar-left">
      <%= render :partial => 'partials/search_form',
                 :locals => {:plh_search => 'Search airport by name ...',
                             :key_search => @key_search, :action => airports_path} %>
    </div>

    <div class="nav navbar-right filters">
      <%= link_to raw("<i class='fa fa-plus'></i> New Airport"), new_airport_path,
                  class: 'btn btn-primary btn-sm',
                  remote: true %>
    </div>
  </div>
</nav>

<div class="box">
  <div class="box-body">
    <div class="row">
      <div class="col-sm-3">
        <%= render partial: 'partials/page_size_selector',
                   locals: {
                       page_size_name: @page_size_name,
                       page_size_value: @page_size_value,
                       total_entries: @airports.total_entries,
                       is_render_script: true}
        %>
      </div>
      <div class="col-sm-9">
        <%= render 'partials/will_paginate', object: @airports %>
      </div>
    </div>

    <table class="table table-hover datatable">
      <thead>
      <tr>
        <th>Name</th>
        <th>Airport Code</th>
        <th>City</th>
        <th class="hidden-xs">State</th>
        <th class="hidden-xs">Country</th>
        <th class="hidden-xs">Time Zone</th>
        <th class="no-sorter"></th>
      </tr>
      </thead>
      <tbody>
      <%= render @airports %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/airports/new.js.erb
$('#popupModal .modal-content').html("<%= j(render 'form') %>");
$('#popupModal .modal-content').prepend("<%= j(render 'layouts/new_modal_title', title: 'Create Airport' ) %>");
$('#popupModal').modal('show');